In [56]:
import numpy as np

In [61]:
grid=input('enter sudoku') #takes in 1d sudoku eg 048301560360008090910670003020000935509010200670020010004002107090100008150834029
grid = [int(i) for i in str(grid)]
grid = np.asarray(grid)
grid = grid.reshape(9,9)
print (grid)

[[0 4 8 3 0 1 5 6 0]
 [3 6 0 0 0 8 0 9 0]
 [9 1 0 6 7 0 0 0 3]
 [0 2 0 0 0 0 9 3 5]
 [5 0 9 0 1 0 2 0 0]
 [6 7 0 0 2 0 0 1 0]
 [0 0 4 0 0 2 1 0 7]
 [0 9 0 1 0 0 0 0 8]
 [1 5 0 8 3 4 0 2 9]]


In [62]:

def check(grid, row, col, val):
    for j in range(0, 9): #for row
        if grid[row,j] == val:
            return False

    for i in range(0, 9): #for col
        if grid[i,col] == val:
            return False

    startRow = (row // 3) * 3 #for square
    startCol = (col // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[(startRow+i),(startCol+j)] == val:
                return False
    return True

def solve():
    for i in range(0, 9):
        for j in range(0, 9):
            if grid[i,j] == 0:
                for val in range(1, 10):
                    if check(grid, i, j, val):
                        grid[i,j] = val
                        solve()
                        grid[i,j] = 0
                return
    print(grid)           
    

solve()

[[7 4 8 3 9 1 5 6 2]
 [3 6 5 2 4 8 7 9 1]
 [9 1 2 6 7 5 4 8 3]
 [4 2 1 7 8 6 9 3 5]
 [5 8 9 4 1 3 2 7 6]
 [6 7 3 5 2 9 8 1 4]
 [8 3 4 9 6 2 1 5 7]
 [2 9 6 1 5 7 3 4 8]
 [1 5 7 8 3 4 6 2 9]]
