In [15]:
import numpy as np

In [16]:
grid=input('enter sudoku') #takes in 1d sudoku eg 748391562365248791912675483421786935589413276673529814834962157296157348157834629
grid = [int(i) for i in str(grid)]
grid = np.asarray(grid)
grid = grid.reshape(9,9)
print (grid)

[[7 4 8 3 9 1 5 6 2]
 [3 6 5 2 4 8 7 9 1]
 [9 1 2 6 7 5 4 8 3]
 [4 2 1 7 8 6 9 3 5]
 [5 8 9 4 1 3 2 7 6]
 [6 7 3 5 2 9 8 1 4]
 [8 3 4 9 6 2 1 5 7]
 [2 9 6 1 5 7 3 4 8]
 [1 5 7 8 3 4 6 2 9]]


In [17]:
def verify(grid):
    #row
    for i in range (9):
        if len(np.unique(grid[i])) < len(grid[i]):
            return False

    #col
    for j in range (9):
        if len(np.unique(grid[:,j])) < len(grid[:,j]):
            return False
        
    #square
    grid=grid.reshape((3, 3, 3, 3)).swapaxes(1, 2).reshape((9,9))
    for k in range (9):
        if len(np.unique(grid[k])) < len(grid[k]):
            return False
    return True

In [18]:
print(verify(grid)) #returns True if sudoku is valid

True
